### ISSUE TITLE
Milestone 3

### ISSUE THREAD

**Issue by lsteiner9** [lsteiner9/scale-scroller#4]
**Documentation (35pts)**
- [x] Project intro + description (3pts)
- [x] Intended users + user stories (3pts)
- [x] Summary of current state of the app (4pts)
- [x] Wireframe diagram (3pts)
- [x] ERD (3pts)
- [x] DDL (3pts)
- [x] Technical requirements/dependencies (3pts)
- [x] Javadoc technical documentation (4pts)
- [x] Copyrights + licenses (3pts)
- [x] Build instructions (3pts)
- [x] Basic user instructions (3pts)

**Implementation (40pts)**
- [x] Multiple screens with intuitive navigation (8pts)
- [x] Use of SQLite database (8pts)
- [x] Dynamic, data-driven UI components (8pts)
- [x] Custom drawable assets (4pts)
- [x] External- or device-based services (7pts)
- [x] Use of shared preferences (5pts)

**Extra credit**
- [ ] Separation of concerns
- [ ] Code quality and style
